alias i="sudo apt install"
alias pogoda="curl https://wttr.in/?0"
alias speedtest="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 "
alias update="sudo apt update && sudo apt upgrade -y"
alias statuswatch="watch -c SYSTEMD_COLORS=1 systemctl status"
alias ekran="sudo systemctl restart gdm3"
